#!/usr/bin/env perl

use strict;
use warnings;

use Storable;
use Mojo::UserAgent;
use Data::Dump qw(dump);

my $url = 'http://localhost:3000/data/edit';
my $max = 1;

my @actions = @ARGV;

my $t = Mojo::UserAgent->new;
$t->max_redirects( 1 );

my $stats;

foreach my $c ( sort {
	my $at = $1 if $a =~ m/(\d+\.\d+)/;
	my $bt = $1 if $b =~ m/(\d+\.\d+)/;
	$at <=> $bt
} @actions ) {

	print "# $c\n";

	my $params = retrieve $c;
	my $hash = ref $params eq 'Mojo::Parameters' ? $params->to_hash : $params;
	$hash->{time} = $1 if $c =~ m{/(\d+\.\d+)\.data\.edit};

	warn "# hash ",dump($hash);

	my $tx = $t->post( $url => form => $hash );
	if ( ! $tx->error ) {
		my $res = $tx->res;
		my $code = $res->code;
		$stats->{$code}++;
		print $code, ' ', $res->body
	} else {
		my $err = $tx->error;
		die "Error: " . $err->{message};
	}

#	last if $max-- == 0;
}

warn "# stats ",dump($stats);